### ISSUE TITLE
How to compile?

### ISSUE THREAD

**Issue by meoso** [emuflight/Pegasus#1]
Or will you make a "Release"? (AppImage)

**Comment by Quick-Flash** [comment]
meoso yes we will be making a release. We just still need to get this working. Hopefully when I get some more spare time I can work on getting this ready to go.

**Comment by Quick-Flash** [comment]
Looking at your github profile it looks like you have done some coding for butterflight in the past. If your interested we would love to have more help on this project!

**Comment by meoso** [comment]
i only renamed the configurator's .desktop file so that it would install correctly in Linux -- it was no coding :( 
:) 
--nerdCopter
